[mainConfig]
appName = "GoAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "ynmkiksslpdgibjg"
email = "1335921685@qq.com"

[redisConfig]
host = "192.168.56.101"
port = 6379
password = "zheshimima"
db = 0

[mysqlConfig]
host = "192.168.56.101"
port = 3306
user = "eino"
password = "einoWord"
databaseName = "GoAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GoAI"
 key= "GoAI"

 [rabbitmqConfig]
  host= "192.168.56.101"
  port= 5672
  username= "TestUser"
  password= "Test"
  vhost= "/"
